<!DOCTYPE html>
<html>
<head>
	<title>COMPLEX QUERIES</title>
</head>
<body>
<h1>COMPLEX QUERIES</h1>
1)RETRIEVE THE 3rd HIGHEST PAID BOOKING
<br>
<hr>
2)RETRIEVE STAFF_ID WHO HAVE NOT GONE FOR DELIVERY 
<br>
<hr>
3)RETRIEVE THE CUSTOMER THAT HAVE NOT DONE ANY BOOKING
<br>
<hr>
4)RETRIEVE THE BRANCH ,NO OF BOOKINGS FOR EACH BRANCH BETWEEN JAN AND FEB 
<br>
<hr>
5)RETRIEVE THE CUSTOMER THAT HAVE NOT DONE ANY BOOKING FROM KOLKATA AND BANGALORE
<br>
<hr>
6)RETRIEVE THE BRANCH MANAGER,BRANCH MANAGER NAME WHERE TOTAL NO OF BOOKINGS>10
<br>
<hr>
7)RETRIEVE THE BRANCH,TOTAL AMOUNT WHERE NO OF BOOKINGS>5
<br>
<hr>
8)RETRIEVE THE CUSTOMER WHO HAS DONE MAX NO OF BOOKINGS FROM BANGALORE
<br>
<hr>
9)RETRIEVE THE CONSIGNMENT NUMBER,CUSTOMER NAME WHICH ARE NOT DELIVERED
<br>
<hr>
 <ul class="pager">
    <li><a href="adm2.html">GO TO HOME</a></li>
  </ul>
</body>
</html>